# Generated by Django 3.1.4 on 2020-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20201227_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='dp',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='upload',
        ),
    ]
