# Generated by Django 3.1.4 on 2020-12-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20201227_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dp',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
