# Generated by Django 3.1.4 on 2020-12-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20201228_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dp',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='templates/static/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='templates/static1/'),
        ),
    ]
