# Generated by Django 3.1.4 on 2021-01-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_auto_20201228_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dp',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
