# Generated by Django 3.1.4 on 2021-01-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_auto_20210101_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dp',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='MyApp/static/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='MyApp/static1/'),
        ),
    ]
